spring:
  data:
    mongodb:
      database: instaclone_auth
      port: 27017

server:
  port: 8081

security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey

